spring:
  application:
    name: GAE

logging:
  level:
    org.fh.gae: debug
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] - [%t] - [%level] %c{40} - %m%n"


gae:
  server:
    port: 9000
    host: 0.0.0.0
  index:
    path: /Users/whf/projects/open/gae/src/main/resources/mock
    name: gae.idx
    incr-path: /Users/whf/projects/open/gae/src/main/resources/mock
    incr-name: gae.idx.incr
    incr-interval: 500
  dict:
    ip: data/ipdict.txt